# Generated by Django 3.1.6 on 2021-02-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45)),
                ('prodcut_price', models.IntegerField(max_length=100)),
                ('product_description', models.IntegerField(max_length=10000)),
                ('product_status', models.BooleanField(max_length=5)),
            ],
        ),
    ]
