# Generated by Django 3.1.6 on 2021-02-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45)),
                ('product_price', models.FloatField(default=0)),
                ('product_category', models.CharField(choices=[('ACC', 'Accessories'), ('B', 'Bags'), ('C', 'Clothes'), ('EL', 'Electronics'), ('FD', 'Food'), ('FUR', 'Furniture + Home Deco'), ('K', 'Kitchen Apps'), ('NO', 'Not Food'), ('SH', 'Shoes'), ('SO', 'Socks'), ('N', 'New')], default='N', max_length=3)),
                ('product_description', models.TextField(max_length=10000)),
            ],
        ),
    ]
