# Generated by Django 3.1.6 on 2021-02-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='c/Users/spend/Desktop/Random_Desktop_Stuff/Pics/Memes/christine.jpg', upload_to=''),
        ),
    ]
