# Generated by Django 3.1.6 on 2021-02-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodcut_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=10000),
        ),
    ]
