# Generated by Django 3.1.6 on 2021-02-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot_backend', '0002_auto_20210209_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_price',
            new_name='product_price',
        ),
    ]
